services:

  app_server:
    build:
      context: .
      dockerfile: cmd/docker/app-server/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - DB_DSN=${DB_DSN}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres_go
    networks:
      - app-network
    volumes:
      - .env:/app/.env




  web_server:
    build:
      context: .
      dockerfile: cmd/docker/web-server/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - DB_DSN=${DB_DSN}
    depends_on:
      - postgres_go
    networks:
      - app-network
    volumes:
      - .env:/app/.env
      - ./static:/app/static




  postgres_go:
    image: postgres:17.4-alpine3.21
    container_name: postgres_go
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authservice
    ports:
      - "5441:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network




  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres_go
    networks:
      - app-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin



volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local



networks:
  app-network:
    driver: bridge
