

services:
  postgres_go:
    image: postgres:17.4-alpine3.21
    container_name: postgres_go
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authservice
    ports:
      - "5441:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
